services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.11
    ports:
      - '5672:5672'
      - '15672:15672'

  orders-mongodb:
    image: mongo:5.0.0
    container_name: orders-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    ports:
      - 27017:27017
